<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

f'./{filename[ss]}_5Min.csv' 파일 하나에 5gb가 넘는다 </br>
그래서 오래 걸림 😥 </br>

In [ ]:
import numpy as np
import pandas as pd

# (추가).. 데이터 용량 줄이기.. 일단은 필요한 링크들만 추출..
filtering = pd.read_excel('./사업지도로만_최종.xlsx')
filtering.head(3)

# filename = 20221107
filename = []

for xx in range(8): # 며칠할껀지
    filename.append(20221107 + xx)

for ss in range(len(filename)):
    df = pd.read_csv(f'./{filename[ss]}_5Min.csv')
    print(filename[ss],'중...')
    df.columns = ['날짜','시간','LINK_ID','도로기관코드','통행속도']
    df.head(3)

    df2 = df.copy()
    df2.head(3)

    ## 경기도

    df2['newone'] = df2['LINK_ID'].astype(str).str[:3]
    df3 = df2[df2['newone'] == '223']
    df3["구분"] = ((df3['시간']-1)/100).astype(int)
    df3
    
    HI = []

    for i in range(len(filtering)):
        HI.append(df3[df3['LINK_ID'] == filtering['LINK_ID'].values.tolist()[i]])

    filtering2 = pd.concat(HI)
    filtering2 = filtering2.reset_index(drop=True)
    filtering2

    filtering2.to_excel(f'./태블로식{filename[ss]}.xlsx')
    
print('FIN')

In [ ]:
BYE = []

for jj in range(len(filename)):
    BYE.append(pd.read_excel(f'./태블로식{filename[jj]}.xlsx'))
    
lastone = pd.concat(BYE)
lastone.to_excel('./태블로식_최종.xlsx')

In [ ]:
lastone

아래는 초기에 짜본 코드 반복문을 안써서 엄~청 길다 (같은 내용을 반복함) </br>
최종 코드는 [[오산시] 링크별 통행속도 구하기_최종.ipynb](https://github.com/7rohj/roadlink_avgspeed/blob/main/%5B%EC%98%A4%EC%82%B0%EC%8B%9C%5D%20%EB%A7%81%ED%81%AC%EB%B3%84%20%ED%86%B5%ED%96%89%EC%86%8D%EB%8F%84%20%EA%B5%AC%ED%95%98%EA%B8%B0_%EC%B5%9C%EC%A2%85.ipynb) 에서 확인할 수 있다.

In [27]:
## 원동로
k_s = [2230017602,2230017601,2230003500,2230003900,2230004200]

A = []

for i in range(len(k_s)):
    df999 = df3[df3['LINK_ID'] == k_s[i]]
    df999 = df999.sort_values(by=['시간'])
    df999 = df999.reset_index(drop=True)
    df9999 = df999.groupby(['구분']).mean()
    
    result = pd.DataFrame(None)
    result['통행속도'] = df9999['통행속도']
    #real_result = result.T
    A.append(result.T)

# 20211107 경기도 상행 통행속도 합침
real_result = pd.concat(A)
real_result = real_result.reset_index(drop=True)
real_result

# link id 합침
linkid = pd.DataFrame(None)
linkid['LINK_ID'] =  k_s
linkid

almostdone = pd.concat([real_result,linkid],axis=1)
almostdone

date = pd.DataFrame(None)
date['날짜'] =df9999['날짜']
date = date.T
date

almostdone2 = pd.concat([date,almostdone])
almostdone2

almostdone2.to_excel(f'./원동로/{filename}_원동로_상행.xlsx')

k_s = [2230017501,2230017502,2230003600,2230004000,2230004100]

A = []

for i in range(len(k_s)):
    df999 = df3[df3['LINK_ID'] == k_s[i]]
    df999 = df999.sort_values(by=['시간'])
    df999 = df999.reset_index(drop=True)
    df9999 = df999.groupby(['구분']).mean()
    
    result = pd.DataFrame(None)
    result['통행속도'] = df9999['통행속도']
    #real_result = result.T
    A.append(result.T)

# 20211107 경기도 상행 통행속도 합침
real_result = pd.concat(A)
real_result = real_result.reset_index(drop=True)
real_result

# link id 합침
linkid = pd.DataFrame(None)
linkid['LINK_ID'] =  k_s
linkid

almostdone = pd.concat([real_result,linkid],axis=1)
almostdone

date = pd.DataFrame(None)
date['날짜'] =df9999['날짜']
date = date.T
date

almostdone2 = pd.concat([date,almostdone])
almostdone2

almostdone2.to_excel(f'./원동로/{filename}_원동로_하행.xlsx')

In [28]:
## 경기대로

k_s = [2230006203,2230006202,2230006201,2230005200,2230004803,2230004802,2230004801]
A = []

for i in range(len(k_s)):
    df999 = df3[df3['LINK_ID'] == k_s[i]]
    df999 = df999.sort_values(by=['시간'])
    df999 = df999.reset_index(drop=True)
    df9999 = df999.groupby(['구분']).mean()
    
    result = pd.DataFrame(None)
    result['통행속도'] = df9999['통행속도']
    #real_result = result.T
    A.append(result.T)

real_result = pd.concat(A)
real_result = real_result.reset_index(drop=True)
real_result

# link id 합침
linkid = pd.DataFrame(None)
linkid['LINK_ID'] =  k_s
linkid

almostdone = pd.concat([real_result,linkid],axis=1)
almostdone

date = pd.DataFrame(None)
date['날짜'] =df9999['날짜']
date = date.T
date

almostdone2 = pd.concat([date,almostdone])
almostdone2

almostdone2.to_excel(f'./경기대로/{filename}_경기대로_상행.xlsx')

## 경기대로_하행
k_s = [2230006103,2230006102,2230006101,2230005100,2230004703,2230004702,2230004701]
A = []

for i in range(len(k_s)):
    df999 = df3[df3['LINK_ID'] == k_s[i]]
    df999 = df999.sort_values(by=['시간'])
    df999 = df999.reset_index(drop=True)
    df9999 = df999.groupby(['구분']).mean()
    
    result = pd.DataFrame(None)
    result['통행속도'] = df9999['통행속도']
    #real_result = result.T
    A.append(result.T)

real_result = pd.concat(A)
real_result = real_result.reset_index(drop=True)
real_result

# link id 합침
linkid = pd.DataFrame(None)
linkid['LINK_ID'] =  k_s
linkid

almostdone = pd.concat([real_result,linkid],axis=1)
almostdone

date = pd.DataFrame(None)
date['날짜'] =df9999['날짜']
date = date.T
date

almostdone2 = pd.concat([date,almostdone])
almostdone2

almostdone2.to_excel(f'./경기대로/{filename}_경기대로_하행.xlsx')

In [29]:
## 남부대로

k_s = [2230073400,2230073200,2230073000,2230001602,2230001400]
A = []

for i in range(len(k_s)):
    df999 = df3[df3['LINK_ID'] == k_s[i]]
    df999 = df999.sort_values(by=['시간'])
    df999 = df999.reset_index(drop=True)
    df9999 = df999.groupby(['구분']).mean()
    
    result = pd.DataFrame(None)
    result['통행속도'] = df9999['통행속도']
    #real_result = result.T
    A.append(result.T)

# 20211107 경기도 상행 통행속도 합침
real_result = pd.concat(A)
real_result = real_result.reset_index(drop=True)
real_result

# link id 합침
linkid = pd.DataFrame(None)
linkid['LINK_ID'] =  k_s
linkid

almostdone = pd.concat([real_result,linkid],axis=1)
almostdone

date = pd.DataFrame(None)
date['날짜'] =df9999['날짜']
date = date.T
date

almostdone2 = pd.concat([date,almostdone])
almostdone2

almostdone2.to_excel(f'./남부대로/{filename}_남부대로_상행.xlsx')

k_s = [2230073300,2230073100,2230072900,2230001501,2230001300]

A = []

for i in range(len(k_s)):
    df999 = df3[df3['LINK_ID'] == k_s[i]]
    df999 = df999.sort_values(by=['시간'])
    df999 = df999.reset_index(drop=True)
    df9999 = df999.groupby(['구분']).mean()
    
    result = pd.DataFrame(None)
    result['통행속도'] = df9999['통행속도']
    #real_result = result.T
    A.append(result.T)

# 20211107 경기도 상행 통행속도 합침
real_result = pd.concat(A)
real_result = real_result.reset_index(drop=True)
real_result

# link id 합침
linkid = pd.DataFrame(None)
linkid['LINK_ID'] =  k_s
linkid

almostdone = pd.concat([real_result,linkid],axis=1)
almostdone

date = pd.DataFrame(None)
date['날짜'] =df9999['날짜']
date = date.T
date

almostdone2 = pd.concat([date,almostdone])
almostdone2

almostdone2.to_excel(f'./남부대로/{filename}_남부대로_하행.xlsx')

In [30]:
## 성호대로 낮은 속도 .. 이상치 나오는 이유 알아내기 및 

df3[df3['LINK_ID'] == 2230028600]

                 날짜    시간       LINK_ID    도로기관코드  통행속도 newone  구분
585471     20221108     0    2230028600  46340006  13.0    223   0
1011301    20221108     5  2230028600.0  46340006  13.0    223   0
2389148    20221108    15    2230028600  46340006  16.0    223   0
4381650    20221108    30    2230028600  46340006  16.0    223   0
4933638    20221108    35    2230028600  46340006  16.0    223   0
...             ...   ...           ...       ...   ...    ...  ..
116003126  20221108  2245  2230028600.0  46340006   5.0    223  22
119953174  20221108  2315  2230028600.0  46340006   6.0    223  23
120998121  20221108  2350    2230028600  46340006   9.0    223  23
122311836  20221108  2345    2230028600  46340006   9.0    223  23
122821958  20221108  2355  2230028600.0  46340006  15.0    223  23

[115 rows x 7 columns]

In [31]:
## 성호대로
k_s = [2230005900,2230005700,2230005302,2230005502,2230026300,2230005503,2230005301,2230028600,2230028200,2230027800]
A = []

for i in range(len(k_s)):
    df999 = df3[df3['LINK_ID'] == k_s[i]]
    df999 = df999.sort_values(by=['시간'])
    df999 = df999.reset_index(drop=True)
    df9999 = df999.groupby(['구분']).mean()
    
    result = pd.DataFrame(None)
    result['통행속도'] = df9999['통행속도']
    #real_result = result.T
    A.append(result.T)

# 20211107 경기도 상행 통행속도 합침
real_result = pd.concat(A)
real_result = real_result.reset_index(drop=True)
real_result

# link id 합침
linkid = pd.DataFrame(None)
linkid['LINK_ID'] =  k_s
linkid

almostdone = pd.concat([real_result,linkid],axis=1)
almostdone

date = pd.DataFrame(None)
date['날짜'] =df9999['날짜']
date = date.T
date

almostdone2 = pd.concat([date,almostdone])
almostdone2

almostdone2.to_excel(f'./성호대로/{filename}_성호대로_상행.xlsx')

k_s = [2230006000,2230005800,2230005603,2230005602,2230026400,2230005402,2230005401,2230028500,2230028100,2230027700]
A = []

for i in range(len(k_s)):
    df999 = df3[df3['LINK_ID'] == k_s[i]]
    df999 = df999.sort_values(by=['시간'])
    df999 = df999.reset_index(drop=True)
    df9999 = df999.groupby(['구분']).mean()
    
    result = pd.DataFrame(None)
    result['통행속도'] = df9999['통행속도']
    #real_result = result.T
    A.append(result.T)

# 20211107 경기도 상행 통행속도 합침
real_result = pd.concat(A)
real_result = real_result.reset_index(drop=True)
real_result

# link id 합침
linkid = pd.DataFrame(None)
linkid['LINK_ID'] =  k_s
linkid

almostdone = pd.concat([real_result,linkid],axis=1)
almostdone

date = pd.DataFrame(None)
date['날짜'] =df9999['날짜']
date = date.T
date

almostdone2 = pd.concat([date,almostdone])
almostdone2

almostdone2.to_excel(f'./성호대로/{filename}_성호대로_하행.xlsx')

In [32]:
## 서부로
k_s = [2230159000,2230159100,2230159302,2230347501,2230347901,2230347701,2230347301]

A = []

for i in range(len(k_s)):
    df999 = df3[df3['LINK_ID'] == k_s[i]]
    df999 = df999.sort_values(by=['시간'])
    df999 = df999.reset_index(drop=True)
    df9999 = df999.groupby(['구분']).mean()
    
    result = pd.DataFrame(None)
    result['통행속도'] = df9999['통행속도']
    #real_result = result.T
    A.append(result.T)

# 20211107 경기도 상행 통행속도 합침
real_result = pd.concat(A)
real_result = real_result.reset_index(drop=True)
real_result

# link id 합침
linkid = pd.DataFrame(None)
linkid['LINK_ID'] =  k_s
linkid

almostdone = pd.concat([real_result,linkid],axis=1)
almostdone

date = pd.DataFrame(None)
date['날짜'] =df9999['날짜']
date = date.T
date

almostdone2 = pd.concat([date,almostdone])
almostdone2

almostdone2.to_excel(f'./서부로/{filename}_서부로_상행.xlsx')

k_s = [2230158800,2230158900,2230159201,2230347601,2230347801,2230347401,2230347201]

A = []

for i in range(len(k_s)):
    df999 = df3[df3['LINK_ID'] == k_s[i]]
    df999 = df999.sort_values(by=['시간'])
    df999 = df999.reset_index(drop=True)
    df9999 = df999.groupby(['구분']).mean()
    
    result = pd.DataFrame(None)
    result['통행속도'] = df9999['통행속도']
    #real_result = result.T
    A.append(result.T)

# 20211107 경기도 상행 통행속도 합침
real_result = pd.concat(A)
real_result = real_result.reset_index(drop=True)
real_result

# link id 합침
linkid = pd.DataFrame(None)
linkid['LINK_ID'] =  k_s
linkid

almostdone = pd.concat([real_result,linkid],axis=1)
almostdone

date = pd.DataFrame(None)
date['날짜'] =df9999['날짜']
date = date.T
date

almostdone2 = pd.concat([date,almostdone])
almostdone2

almostdone2.to_excel(f'./서부로/{filename}_서부로_하행.xlsx')

In [33]:
## 경기동로

k_s = [2230007902,2230007903,2230007904,2230007905,2230007906,2230007907,2230007908,2230007909,2230007700,2330018732]

A = []

for i in range(len(k_s)):
    df999 = df3[df3['LINK_ID'] == k_s[i]]
    df999 = df999.sort_values(by=['시간'])
    df999 = df999.reset_index(drop=True)
    df9999 = df999.groupby(['구분']).mean()
    
    result = pd.DataFrame(None)
    result['통행속도'] = df9999['통행속도']
    #real_result = result.T
    A.append(result.T)

# 20211107 경기도 상행 통행속도 합침
real_result = pd.concat(A)
real_result = real_result.reset_index(drop=True)
real_result

# link id 합침
linkid = pd.DataFrame(None)
linkid['LINK_ID'] =  k_s
linkid

almostdone = pd.concat([real_result,linkid],axis=1)
almostdone

date = pd.DataFrame(None)
date['날짜'] =df9999['날짜']
date = date.T
date

almostdone2 = pd.concat([date,almostdone])
almostdone2

almostdone2.to_excel(f'./경기동로/{filename}_경기동로_상행.xlsx')

k_s = [2230008002,2230008003,2230008004,2230008005,2230008006,2230008007,2230008008,2230008009,2230007800,2330018812]

A = []

for i in range(len(k_s)):
    df999 = df3[df3['LINK_ID'] == k_s[i]]
    df999 = df999.sort_values(by=['시간'])
    df999 = df999.reset_index(drop=True)
    df9999 = df999.groupby(['구분']).mean()
    
    result = pd.DataFrame(None)
    result['통행속도'] = df9999['통행속도']
    #real_result = result.T
    A.append(result.T)

# 20211107 경기도 상행 통행속도 합침
real_result = pd.concat(A)
real_result = real_result.reset_index(drop=True)
real_result

# link id 합침
linkid = pd.DataFrame(None)
linkid['LINK_ID'] =  k_s
linkid

almostdone = pd.concat([real_result,linkid],axis=1)
almostdone

date = pd.DataFrame(None)
date['날짜'] =df9999['날짜']
date = date.T
date

almostdone2 = pd.concat([date,almostdone])
almostdone2

almostdone2.to_excel(f'./경기동로/{filename}_경기동로_하행.xlsx')

In [34]:
## 오산로

k_s = [2230017300,2230012901,2230012902,2230073500]
A = []

for i in range(len(k_s)):
    df999 = df3[df3['LINK_ID'] == k_s[i]]
    df999 = df999.sort_values(by=['시간'])
    df999 = df999.reset_index(drop=True)
    df9999 = df999.groupby(['구분']).mean()
    
    result = pd.DataFrame(None)
    result['통행속도'] = df9999['통행속도']
    #real_result = result.T
    A.append(result.T)

# 20211107 경기도 상행 통행속도 합침
real_result = pd.concat(A)
real_result = real_result.reset_index(drop=True)
real_result

# link id 합침
linkid = pd.DataFrame(None)
linkid['LINK_ID'] =  k_s
linkid

almostdone = pd.concat([real_result,linkid],axis=1)
almostdone

date = pd.DataFrame(None)
date['날짜'] =df9999['날짜']
date = date.T
date

almostdone2 = pd.concat([date,almostdone])
almostdone2

almostdone2.to_excel(f'./오산로/{filename}_오산로_상행.xlsx')

k_s = [2230017400,2230013001,2230013002,2230073600]
A = []

for i in range(len(k_s)):
    df999 = df3[df3['LINK_ID'] == k_s[i]]
    df999 = df999.sort_values(by=['시간'])
    df999 = df999.reset_index(drop=True)
    df9999 = df999.groupby(['구분']).mean()
    
    result = pd.DataFrame(None)
    result['통행속도'] = df9999['통행속도']
    #real_result = result.T
    A.append(result.T)

# 20211107 경기도 상행 통행속도 합침
real_result = pd.concat(A)
real_result = real_result.reset_index(drop=True)
real_result

# link id 합침
linkid = pd.DataFrame(None)
linkid['LINK_ID'] =  k_s
linkid

almostdone = pd.concat([real_result,linkid],axis=1)
almostdone

date = pd.DataFrame(None)
date['날짜'] =df9999['날짜']
date = date.T
date

almostdone2 = pd.concat([date,almostdone])
almostdone2

almostdone2.to_excel(f'./오산로/{filename}_오산로_하행.xlsx')

In [35]:
## 문시로
k_s = [2230160202,2230160201,2230161102,2230161101,2230162000]
A = []

for i in range(len(k_s)):
    df999 = df3[df3['LINK_ID'] == k_s[i]]
    df999 = df999.sort_values(by=['시간'])
    df999 = df999.reset_index(drop=True)
    df9999 = df999.groupby(['구분']).mean()
    
    result = pd.DataFrame(None)
    result['통행속도'] = df9999['통행속도']
    #real_result = result.T
    A.append(result.T)

# 20211107 경기도 상행 통행속도 합침
real_result = pd.concat(A)
real_result = real_result.reset_index(drop=True)
real_result

# link id 합침
linkid = pd.DataFrame(None)
linkid['LINK_ID'] =  k_s
linkid

almostdone = pd.concat([real_result,linkid],axis=1)
almostdone

date = pd.DataFrame(None)
date['날짜'] =df9999['날짜']
date = date.T
date

almostdone2 = pd.concat([date,almostdone])
almostdone2

almostdone2.to_excel(f'./문시로/{filename}_문시로_상행.xlsx')

k_s = [2230160301,2230160302,2230161001,2230161002,2230162100]
A = []

for i in range(len(k_s)):
    df999 = df3[df3['LINK_ID'] == k_s[i]]
    df999 = df999.sort_values(by=['시간'])
    df999 = df999.reset_index(drop=True)
    df9999 = df999.groupby(['구분']).mean()
    
    result = pd.DataFrame(None)
    result['통행속도'] = df9999['통행속도']
    #real_result = result.T
    A.append(result.T)

# 20211107 경기도 상행 통행속도 합침
real_result = pd.concat(A)
real_result = real_result.reset_index(drop=True)
real_result

# link id 합침
linkid = pd.DataFrame(None)
linkid['LINK_ID'] =  k_s
linkid

almostdone = pd.concat([real_result,linkid],axis=1)
almostdone

date = pd.DataFrame(None)
date['날짜'] =df9999['날짜']
date = date.T
date

almostdone2 = pd.concat([date,almostdone])
almostdone2

almostdone2.to_excel(f'./문시로/{filename}_문시로_하행.xlsx')

끗